# Generated by Django 4.0.5 on 2022-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kupan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khuán',
            options={'ordering': ['-id'], 'verbose_name': 'Khuán', 'verbose_name_plural': 'Khuán'},
        ),
    ]
