# Generated by Django 4.1.5 on 2023-05-23 12:47

from django.db import migrations, models
import kupan.models


class Migration(migrations.Migration):

    dependencies = [
        ('kupan', '0002_alter_khuán_新文章tī面頂較好選'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lē',
            name='音檔',
            field=models.FileField(blank=True, storage=kupan.models.KuPanStorage(), upload_to=''),
        ),
    ]
