# Generated by Django 2.1.3 on 2018-12-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='句表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('音檔', models.FileField(blank=True, upload_to='')),
                ('漢字', models.CharField(blank=True, max_length=200)),
                ('臺羅', models.CharField(blank=True, max_length=200)),
                ('修改時間', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='文章表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('文章名', models.TextField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='句表',
            name='來源',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='SuiSiannAdminApp.文章表'),
        ),
    ]
