# Generated by Django 2.1.3 on 2018-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='對齊狀態',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='句表',
            name='音檔',
            field=models.FileField(blank=True, unique=True, upload_to=''),
        ),
    ]
