# Generated by Django 2.1.3 on 2018-12-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0002_auto_20181204_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='句表',
            name='來源',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='SuiSiannAdminApp.文章表'),
        ),
    ]
