# Generated by Django 2.1.3 on 2018-12-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0003_auto_20181204_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='句表',
            name='音檔',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='文章表',
            name='文章名',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
