# Generated by Django 2.1.3 on 2018-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0004_auto_20181204_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='句表',
            name='對齊狀態',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
