# Generated by Django 2.1.3 on 2019-01-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0006_auto_20181207_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='備註',
            field=models.TextField(blank=True),
        ),
    ]
