# Generated by Django 2.1.3 on 2019-01-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0007_句表_備註'),
    ]

    operations = [
        migrations.CreateModel(
            name='語料狀況表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('狀況', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': '語料狀況表',
                'verbose_name_plural': '語料狀況表',
            },
        ),
        migrations.AlterModelOptions(
            name='句表',
            options={'verbose_name': '句表', 'verbose_name_plural': '句表'},
        ),
        migrations.AlterModelOptions(
            name='文章表',
            options={'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AddField(
            model_name='句表',
            name='語料狀況',
            field=models.ManyToManyField(blank=True, to='SuiSiannAdminApp.語料狀況表'),
        ),
    ]
