# Generated by Django 2.1.3 on 2019-01-03 03:31

from django.db import migrations, models
from django.db.models import F


def 備份原始漢羅(apps, schema_editor):
    句表 = apps.get_model('SuiSiannAdminApp', '句表')
    句表.objects.all().update(原始漢字=F('漢字'), 原始臺羅=F('臺羅'))


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0008_auto_20190103_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='原始漢字',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='句表',
            name='原始臺羅',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RunPython(備份原始漢羅, lambda *x:x),
    ]
