# Generated by Django 2.1.7 on 2019-02-21 07:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0011_句表_漢羅欄位加長'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='kaldi切音時間',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
