# Generated by Django 2.1.7 on 2019-04-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0012_句表_kaldi切音時間'),
    ]

    operations = [
        migrations.AlterField(
            model_name='句表',
            name='來源',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='句', to='SuiSiannAdminApp.文章表'),
        ),
    ]
