# Generated by Django 3.2.4 on 2021-07-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0013_auto_20190424_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='句表',
            old_name='原始臺羅',
            new_name='原始羅馬字',
        ),
        migrations.RenameField(
            model_name='句表',
            old_name='臺羅',
            new_name='羅馬字含口語調',
        ),
    ]
