# Generated by Django 3.2.4 on 2021-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0014_rename_原始臺羅_句表_原始羅馬字'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='羅馬字',
            field=models.TextField(default='lomaji', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='句表',
            name='原始漢字',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='句表',
            name='原始羅馬字',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='句表',
            name='漢字',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='句表',
            name='羅馬字含口語調',
            field=models.TextField(),
        ),
    ]
