# Generated by Django 3.2.5 on 2021-08-02 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SuiSiannAdminApp', '0016_auto_20210712_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='修改人',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
