# Generated by Django 4.1.5 on 2023-05-23 12:47

import SuiSiannAdminApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0017_句表_修改人'),
    ]

    operations = [
        migrations.AddField(
            model_name='句表',
            name='S3音檔',
            field=models.FileField(editable=False, null=True, storage=SuiSiannAdminApp.models.KuStorage(), upload_to=''),
        ),
    ]
