# Generated by Django 4.1.5 on 2023-05-23 12:48

from django.db import migrations


def 設定S3音檔(apps, schema_editor):
    句表 = apps.get_model('SuiSiannAdminApp', '句表')
    for ku in 句表.objects.all():
        ku.S3音檔 = ku.音檔
        ku.save()


class Migration(migrations.Migration):

    dependencies = [
        ('SuiSiannAdminApp', '0018_句表_s3音檔'),
    ]

    operations = [
        migrations.RunPython(設定S3音檔, lambda *x:x),
    ]
