# Generated by Django 4.0.6 on 2022-07-19 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sekchi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sekchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('音檔所在', models.FilePathField(match='.*.wav', max_length=1000, path=sekchi.models.siktsi_path, unique=True)),
                ('漢字', models.TextField()),
                ('羅馬字含口語調', models.TextField()),
                ('羅馬字', models.TextField(editable=False)),
                ('part', models.CharField(max_length=5)),
                ('編號', models.CharField(max_length=10)),
                ('修改時間', models.DateTimeField(auto_now=True)),
                ('修改人', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '汐止腔語料',
                'verbose_name_plural': '汐止腔語料',
            },
        ),
    ]
