# Generated by Django 4.0.6 on 2022-07-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekchi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
