# Generated by Django 4.0.6 on 2022-07-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekchi',
            name='來源',
            field=models.CharField(db_index=True, default='M̄-tsai', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sekchi',
            name='part',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sekchi',
            name='編號',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
