# Generated by Django 4.0.5 on 2022-07-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0002_alter_sekchi_音檔所在'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekchi',
            name='音檔所在',
            field=models.FilePathField(match='.*.wav', max_length=1000, path='/mnt/bfc3207f-8834-44cf-9206-3a13bda7bd35/home/fafofafoy/git/SuiSiann/SuiSiann-KauTui/汐止媠聲', unique=True),
        ),
    ]
