# Generated by Django 4.0.6 on 2022-08-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0005_sekchi_對齊狀態'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekchi',
            name='對齊狀態',
            field=models.BooleanField(),
        ),
    ]
