# Generated by Django 4.0.6 on 2022-08-23 05:51

from django.db import migrations, models

from SuiSiannAdminApp.management.檢查對齊狀態 import 檢查對齊狀態
from phiaua.clean import clean_html


class Migration(migrations.Migration):

    def kiamtsa_khaugitiau(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        Sekchi = apps.get_model("sekchi", "Sekchi")
        for obj in Sekchi.objects.all():
            khaugi_html = clean_html(obj.羅馬字含口語調)
            obj.口語調狀態 = 檢查對齊狀態(obj.漢字, obj.羅馬字, khaugi_html)
            obj.save()

    dependencies = [
        ('sekchi', '0006_alter_sekchi_對齊狀態')
    ]

    operations = [
        migrations.AddField(
            model_name='sekchi',
            name='口語調狀態',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(kiamtsa_khaugitiau)
    ]
