# Generated by Django 4.0.6 on 2022-08-23 07:44

from django.db import migrations
from phiaua.clean import piann_haikhau_piantiau


class Migration(migrations.Migration):

    def haikhau_piantiau(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        Sekchi = apps.get_model("sekchi", "Sekchi")
        for obj in Sekchi.objects.all():
            obj.羅馬字含口語調 = piann_haikhau_piantiau(obj.羅馬字含口語調)
            obj.save()

    dependencies = [
        ('sekchi', '0007_sekchi_口語調狀態'),
    ]

    operations = [
        migrations.RunPython(haikhau_piantiau)
    ]
