# Generated by Django 4.1.5 on 2023-05-23 12:47

from django.db import migrations, models
import sekchi.models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0008_換掉海口腔變調'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekchi',
            name='S3音檔',
            field=models.FileField(editable=False, null=True, storage=sekchi.models.KuStorage(), upload_to=''),
        ),
    ]
