# Generated by Django 4.1.5 on 2023-05-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekchi', '0011_設定S3音檔'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekchi',
            name='修改時間',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
