# Generated by Django 3.2.4 on 2021-07-13 03:09

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khuán',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miâ', models.CharField(max_length=30, unique=True)),
                ('iūnn', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Khuán',
                'verbose_name_plural': 'Khuán',
            },
        ),
        migrations.CreateModel(
            name='Luī',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miâ', models.CharField(max_length=30, unique=True)),
                ('siktsuí', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('singāu', models.PositiveIntegerField()),
                ('khuán', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='luī', to='phiaua.khuán')),
            ],
            options={
                'verbose_name': 'Luī',
                'verbose_name_plural': 'Luī',
            },
        ),
        migrations.AddConstraint(
            model_name='luī',
            constraint=models.UniqueConstraint(fields=('khuán', 'miâ'), name='khuán-luī'),
        ),
    ]
