# Generated by Django 3.2.4 on 2021-07-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phiaua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luī',
            options={'ordering': ['singāu'], 'verbose_name': 'Luī', 'verbose_name_plural': 'Luī'},
        ),
    ]
